package com.abhaycloud.composeccp.utils

import com.abhaycloud.composeccp.R

object CountryData {
    val countries = listOf(
        CountryModel(code = "AF", name = "Afghanistan", dialCode = "+93", icon = R.drawable.af),
        CountryModel(code = "AX", name = "Aland Islands", dialCode = "+358", icon = R.drawable.ax),
        CountryModel(code = "AL", name = "Albania", dialCode = "+355", icon = R.drawable.al),
        CountryModel(code = "DZ", name = "Algeria", dialCode = "+213", icon = R.drawable.dz),
        CountryModel(code = "AS", name = "American Samoa", dialCode = "+1684", icon = R.drawable.`as`),
        CountryModel(code = "AD", name = "Andorra", dialCode = "+376", icon = R.drawable.ad),
        CountryModel(code = "AO", name = "Angola", dialCode = "+244", icon = R.drawable.ao),
        CountryModel(code = "AI", name = "Anguilla", dialCode = "+1264", icon = R.drawable.ai),
        CountryModel(code = "AQ", name = "Antarctica", dialCode = "+672", icon = R.drawable.aq),
        CountryModel(code = "AG", name = "Antigua & Barbuda", dialCode = "+1268", icon = R.drawable.ag),
        CountryModel(code = "AR", name = "Argentina", dialCode = "+54", icon = R.drawable.ar),
        CountryModel(code = "AM", name = "Armenia", dialCode = "+374", icon = R.drawable.am),
        CountryModel(code = "AW", name = "Aruba", dialCode = "+297", icon = R.drawable.aw),
        CountryModel(code = "AU", name = "Australia", dialCode = "+61", icon = R.drawable.au),
        CountryModel(code = "AT", name = "Austria", dialCode = "+43", icon = R.drawable.at),
        CountryModel(code = "AZ", name = "Azerbaijan", dialCode = "+994", icon = R.drawable.az),
        CountryModel(code = "BS", name = "Bahamas", dialCode = "+1242", icon = R.drawable.bs),
        CountryModel(code = "BH", name = "Bahrain", dialCode = "+973", icon = R.drawable.bh),
        CountryModel(code = "BD", name = "Bangladesh", dialCode = "+880", icon = R.drawable.bd),
        CountryModel(code = "BB", name = "Barbados", dialCode = "+1246", icon = R.drawable.bb),
        CountryModel(code = "BY", name = "Belarus", dialCode = "+375", icon = R.drawable.by),
        CountryModel(code = "BE", name = "Belgium", dialCode = "+32", icon = R.drawable.be),
        CountryModel(code = "BZ", name = "Belize", dialCode = "+501", icon = R.drawable.bz),
        CountryModel(code = "BJ", name = "Benin", dialCode = "+229", icon = R.drawable.bj),
        CountryModel(code = "BM", name = "Bermuda", dialCode = "+1441", icon = R.drawable.bm),
        CountryModel(code = "BT", name = "Bhutan", dialCode = "+975", icon = R.drawable.bt),
        CountryModel(code = "BO", name = "Bolivia", dialCode = "+591", icon = R.drawable.bo),
        CountryModel(code = "BA", name = "Bosnia & Herzegovina", dialCode = "+387", icon = R.drawable.ba),
        CountryModel(code = "BW", name = "Botswana", dialCode = "+267", icon = R.drawable.bw),
        CountryModel(code = "BR", name = "Brazil", dialCode = "+55", icon = R.drawable.br),
        CountryModel(code = "IO", name = "British Indian Ocean Territory", dialCode = "+246", icon = R.drawable.io),
        CountryModel(code = "BN", name = "Brunei Darussalam", dialCode = "+673", icon = R.drawable.bn),
        CountryModel(code = "BG", name = "Bulgaria", dialCode = "+359", icon = R.drawable.bg),
        CountryModel(code = "BF", name = "Burkina Faso", dialCode = "+226", icon = R.drawable.bf),
        CountryModel(code = "BI", name = "Burundi", dialCode = "+257", icon = R.drawable.bi),
        CountryModel(code = "KH", name = "Cambodia", dialCode = "+855", icon = R.drawable.kh),
        CountryModel(code = "CM", name = "Cameroon", dialCode = "+237", icon = R.drawable.cm),
        CountryModel(code = "CA", name = "Canada", dialCode = "+1", icon = R.drawable.ca),
        CountryModel(code = "CV", name = "Cape Verde", dialCode = "+238", icon = R.drawable.cv),
        CountryModel(code = "KY", name = "Cayman Islands", dialCode = "+345", icon = R.drawable.ky),
        CountryModel(code = "CF", name = "Central African Republic", dialCode = "+236", icon = R.drawable.cf),
        CountryModel(code = "TD", name = "Chad", dialCode = "+235", icon = R.drawable.td),
        CountryModel(code = "CL", name = "Chile", dialCode = "+56", icon = R.drawable.cl),
        CountryModel(code = "CN", name = "China", dialCode = "+86", icon = R.drawable.cn),
        CountryModel(code = "CX", name = "Christmas Island", dialCode = "+61", icon = R.drawable.cx),
        CountryModel(code = "CC", name = "Cocos (Keeling) Islands", dialCode = "+61", icon = R.drawable.cc),
        CountryModel(code = "CO", name = "Colombia", dialCode = "+57", icon = R.drawable.co),
        CountryModel(code = "KM", name = "Comoros", dialCode = "+269", icon = R.drawable.km),
        CountryModel(code = "CG", name = "Congo - Brazzaville", dialCode = "+242", icon = R.drawable.cg),
        CountryModel(code = "CD", name = "Congo - Kinshasa", dialCode = "+243", icon = R.drawable.cd),
        CountryModel(code = "CK", name = "Cook Islands", dialCode = "+682", icon = R.drawable.ck),
        CountryModel(code = "CR", name = "Costa Rica", dialCode = "+506", icon = R.drawable.cr),
        CountryModel(code = "CI", name = "Cote d'Ivoire", dialCode = "+225", icon = R.drawable.ci),
        CountryModel(code = "HR", name = "Croatia", dialCode = "+385", icon = R.drawable.hr),
        CountryModel(code = "CU", name = "Cuba", dialCode = "+53", icon = R.drawable.cu),
        CountryModel(code = "CY", name = "Cyprus", dialCode = "+357", icon = R.drawable.cy),
        CountryModel(code = "CZ", name = "Czech Republic", dialCode = "+420", icon = R.drawable.cz),
        CountryModel(code = "DK", name = "Denmark", dialCode = "+45", icon = R.drawable.dk),
        CountryModel(code = "DJ", name = "Djibouti", dialCode = "+253", icon = R.drawable.dj),
        CountryModel(code = "DM", name = "Dominica", dialCode = "+1767", icon = R.drawable.dm),
        CountryModel(code = "DO", name = "Dominican Republic", dialCode = "+1849", icon = R.drawable.ic_do),
        CountryModel(code = "EC", name = "Ecuador", dialCode = "+593", icon = R.drawable.ec),
        CountryModel(code = "EG", name = "Egypt", dialCode = "+20", icon = R.drawable.eg),
        CountryModel(code = "SV", name = "El Salvador", dialCode = "+503", icon = R.drawable.sv),
        CountryModel(code = "GQ", name = "Equatorial Guinea", dialCode = "+240", icon = R.drawable.gq),
        CountryModel(code = "ER", name = "Eritrea", dialCode = "+291", icon = R.drawable.er),
        CountryModel(code = "EE", name = "Estonia", dialCode = "+372", icon = R.drawable.ee),
        CountryModel(code = "ET", name = "Ethiopia", dialCode = "+251", icon = R.drawable.et),
        CountryModel(code = "FK", name = "Falkland Islands (Malvinas)", dialCode = "+500", icon = R.drawable.fk),
        CountryModel(code = "FO", name = "Faroe Islands", dialCode = "+298", icon = R.drawable.fo),
        CountryModel(code = "FJ", name = "Fiji", dialCode = "+679", icon = R.drawable.fj),
        CountryModel(code = "FI", name = "Finland", dialCode = "+358", icon = R.drawable.fi),
        CountryModel(code = "FR", name = "France", dialCode = "+33", icon = R.drawable.fr),
        CountryModel(code = "GF", name = "French Guiana", dialCode = "+594", icon = R.drawable.gf),
        CountryModel(code = "PF", name = "French Polynesia", dialCode = "+689", icon = R.drawable.pf),
        CountryModel(code = "GA", name = "Gabon", dialCode = "+241", icon = R.drawable.ga),
        CountryModel(code = "GM", name = "Gambia", dialCode = "+220", icon = R.drawable.gm),
        CountryModel(code = "GE", name = "Georgia", dialCode = "+995", icon = R.drawable.ge),
        CountryModel(code = "DE", name = "Germany", dialCode = "+49", icon = R.drawable.de),
        CountryModel(code = "GH", name = "Ghana", dialCode = "+233", icon = R.drawable.gh),
        CountryModel(code = "GI", name = "Gibraltar", dialCode = "+350", icon = R.drawable.gi),
        CountryModel(code = "GR", name = "Greece", dialCode = "+30", icon = R.drawable.gr),
        CountryModel(code = "GL", name = "Greenland", dialCode = "+299", icon = R.drawable.gl),
        CountryModel(code = "GD", name = "Grenada", dialCode = "+1473", icon = R.drawable.gd),
        CountryModel(code = "GP", name = "Guadeloupe", dialCode = "+590", icon = R.drawable.gp),
        CountryModel(code = "GU", name = "Guam", dialCode = "+1671", icon = R.drawable.gu),
        CountryModel(code = "GT", name = "Guatemala", dialCode = "+502", icon = R.drawable.gt),
        CountryModel(code = "GG", name = "Guernsey", dialCode = "+44", icon = R.drawable.gg),
        CountryModel(code = "GN", name = "Guinea", dialCode = "+224", icon = R.drawable.gn),
        CountryModel(code = "GW", name = "Guinea-Bissau", dialCode = "+245", icon = R.drawable.gw),
        CountryModel(code = "GY", name = "Guyana", dialCode = "+595", icon = R.drawable.gy),
        CountryModel(code = "HT", name = "Haiti", dialCode = "+509", icon = R.drawable.ht),
        CountryModel(code = "VA", name = "Holy See (Vatican City State)", dialCode = "+379", icon = R.drawable.va),
        CountryModel(code = "HN", name = "Honduras", dialCode = "+504", icon = R.drawable.hn),
        CountryModel(code = "HK", name = "Hong Kong", dialCode = "+852", icon = R.drawable.hk),
        CountryModel(code = "HU", name = "Hungary", dialCode = "+36", icon = R.drawable.hu),
        CountryModel(code = "IS", name = "Iceland", dialCode = "+354", icon = R.drawable.`is`),
        CountryModel(code = "IN", name = "India", dialCode = "+91", icon = R.drawable.`in`),
        CountryModel(code = "ID", name = "Indonesia", dialCode = "+62", icon = R.drawable.id),
        CountryModel(code = "IR", name = "Iran", dialCode = "+98", icon = R.drawable.ir),
        CountryModel(code = "IQ", name = "Iraq", dialCode = "+964", icon = R.drawable.iq),
        CountryModel(code = "IE", name = "Ireland", dialCode = "+353", icon = R.drawable.ie),
        CountryModel(code = "IM", name = "Isle of Man", dialCode = "+44", icon = R.drawable.im),
        CountryModel(code = "IL", name = "Israel", dialCode = "+972", icon = R.drawable.il),
        CountryModel(code = "IT", name = "Italy", dialCode = "+39", icon = R.drawable.it),
        CountryModel(code = "JM", name = "Jamaica", dialCode = "+1876", icon = R.drawable.jm),
        CountryModel(code = "JP", name = "Japan", dialCode = "+81", icon = R.drawable.jp),
        CountryModel(code = "JE", name = "Jersey", dialCode = "+44", icon = R.drawable.je),
        CountryModel(code = "JO", name = "Jordan", dialCode = "+962", icon = R.drawable.jo),
        CountryModel(code = "KZ", name = "Kazakhstan", dialCode = "+77", icon = R.drawable.kz),
        CountryModel(code = "KE", name = "Kenya", dialCode = "+254", icon = R.drawable.ke),
        CountryModel(code = "KI", name = "Kiribati", dialCode = "+686", icon = R.drawable.ki),
        CountryModel(code = "KP", name = "Korea (North)", dialCode = "+850", icon = R.drawable.kp),
        CountryModel(code = "KR", name = "Korea (South)", dialCode = "+82", icon = R.drawable.kr),
        CountryModel(code = "KW", name = "Kuwait", dialCode = "+965", icon = R.drawable.kw),
        CountryModel(code = "KG", name = "Kyrgyzstan", dialCode = "+996", icon = R.drawable.kg),
        CountryModel(code = "LA", name = "Laos", dialCode = "+856", icon = R.drawable.la),
        CountryModel(code = "LV", name = "Latvia", dialCode = "+371", icon = R.drawable.lv),
        CountryModel(code = "LB", name = "Lebanon", dialCode = "+961", icon = R.drawable.lb),
        CountryModel(code = "LS", name = "Lesotho", dialCode = "+266", icon = R.drawable.ls),
        CountryModel(code = "LR", name = "Liberia", dialCode = "+231", icon = R.drawable.lr),
        CountryModel(code = "LY", name = "Libyan Arab Jamahiriya", dialCode = "+218", icon = R.drawable.ly),
        CountryModel(code = "LI", name = "Liechtenstein", dialCode = "+423", icon = R.drawable.li),
        CountryModel(code = "LT", name = "Lithuania", dialCode = "+370", icon = R.drawable.lt),
        CountryModel(code = "LU", name = "Luxembourg", dialCode = "+352", icon = R.drawable.lu),
        CountryModel(code = "MO", name = "Macao", dialCode = "+853", icon = R.drawable.mo),
        CountryModel(code = "MK", name = "Macedonia", dialCode = "+389", icon = R.drawable.mk),
        CountryModel(code = "MG", name = "Madagascar", dialCode = "+261", icon = R.drawable.mg),
        CountryModel(code = "MW", name = "Malawi", dialCode = "+265", icon = R.drawable.mw),
        CountryModel(code = "MY", name = "Malaysia", dialCode = "+60", icon = R.drawable.my),
        CountryModel(code = "MV", name = "Maldives", dialCode = "+960", icon = R.drawable.mv),
        CountryModel(code = "ML", name = "Mali", dialCode = "+223", icon = R.drawable.ml),
        CountryModel(code = "MT", name = "Malta", dialCode = "+356", icon = R.drawable.mt),
        CountryModel(code = "MH", name = "Marshall Islands", dialCode = "+692", icon = R.drawable.mh),
        CountryModel(code = "MQ", name = "Martinique", dialCode = "+596", icon = R.drawable.mq),
        CountryModel(code = "MR", name = "Mauritania", dialCode = "+222", icon = R.drawable.mr),
        CountryModel(code = "MU", name = "Mauritius", dialCode = "+230", icon = R.drawable.mu),
        CountryModel(code = "YT", name = "Mayotte", dialCode = "+262", icon = R.drawable.yt),
        CountryModel(code = "MX", name = "Mexico", dialCode = "+52", icon = R.drawable.mx),
        CountryModel(code = "FM", name = "Micronesia", dialCode = "+691", icon = R.drawable.fm),
        CountryModel(code = "MD", name = "Moldova", dialCode = "+373", icon = R.drawable.md),
        CountryModel(code = "MC", name = "Monaco", dialCode = "+377", icon = R.drawable.mc),
        CountryModel(code = "MN", name = "Mongolia", dialCode = "+976", icon = R.drawable.mn),
        CountryModel(code = "ME", name = "Montenegro", dialCode = "+382", icon = R.drawable.me),
        CountryModel(code = "MS", name = "Montserrat", dialCode = "+1664", icon = R.drawable.ms),
        CountryModel(code = "MA", name = "Morocco", dialCode = "+212", icon = R.drawable.ma),
        CountryModel(code = "MZ", name = "Mozambique", dialCode = "+258", icon = R.drawable.mz),
        CountryModel(code = "MM", name = "Myanmar", dialCode = "+95", icon = R.drawable.mm),
        CountryModel(code = "NA", name = "Namibia", dialCode = "+264", icon = R.drawable.na),
        CountryModel(code = "NR", name = "Nauru", dialCode = "+674", icon = R.drawable.nr),
        CountryModel(code = "NP", name = "Nepal", dialCode = "+977", icon = R.drawable.np),
        CountryModel(code = "NL", name = "Netherlands", dialCode = "+31", icon = R.drawable.nl),
        CountryModel(code = "NC", name = "New Caledonia", dialCode = "+687", icon = R.drawable.nc),
        CountryModel(code = "NZ", name = "New Zealand", dialCode = "+64", icon = R.drawable.nz),
        CountryModel(code = "NI", name = "Nicaragua", dialCode = "+505", icon = R.drawable.ni),
        CountryModel(code = "NE", name = "Niger", dialCode = "+227", icon = R.drawable.ne),
        CountryModel(code = "NG", name = "Nigeria", dialCode = "+234", icon = R.drawable.ng),
        CountryModel(code = "NU", name = "Niue", dialCode = "+683", icon = R.drawable.nu),
        CountryModel(code = "NF", name = "Norfolk Island", dialCode = "+672", icon = R.drawable.nf),
        CountryModel(code = "KP", name = "North Korea", dialCode = "+850", icon = R.drawable.kp),
        CountryModel(code = "MP", name = "Northern Mariana Islands", dialCode = "+1670", icon = R.drawable.mp),
        CountryModel(code = "NO", name = "Norway", dialCode = "+47", icon = R.drawable.no),
        CountryModel(code = "OM", name = "Oman", dialCode = "+968", icon = R.drawable.om),
        CountryModel(code = "PK", name = "Pakistan", dialCode = "+92", icon = R.drawable.pk),
        CountryModel(code = "PW", name = "Palau", dialCode = "+680", icon = R.drawable.pw),
        CountryModel(code = "PS", name = "Palestinian Territories", dialCode = "+970", icon = R.drawable.ps),
        CountryModel(code = "PA", name = "Panama", dialCode = "+507", icon = R.drawable.pa),
        CountryModel(code = "PG", name = "Papua New Guinea", dialCode = "+675", icon = R.drawable.pg),
        CountryModel(code = "PY", name = "Paraguay", dialCode = "+595", icon = R.drawable.py),
        CountryModel(code = "PE", name = "Peru", dialCode = "+51", icon = R.drawable.pe),
        CountryModel(code = "PH", name = "Philippines", dialCode = "+63", icon = R.drawable.ph),
        CountryModel(code = "PL", name = "Poland", dialCode = "+48", icon = R.drawable.pl),
        CountryModel(code = "PT", name = "Portugal", dialCode = "+351", icon = R.drawable.pt),
        CountryModel(code = "PR", name = "Puerto Rico", dialCode = "+1939", icon = R.drawable.pr),
        CountryModel(code = "QA", name = "Qatar", dialCode = "+974", icon = R.drawable.qa),
        CountryModel(code = "RE", name = "Reunion", dialCode = "+262", icon = R.drawable.re),
        CountryModel(code = "RO", name = "Romania", dialCode = "+40", icon = R.drawable.ro),
        CountryModel(code = "RU", name = "Russia", dialCode = "+7", icon = R.drawable.ru),
        CountryModel(code = "RW", name = "Rwanda", dialCode = "+250", icon = R.drawable.rw),
        CountryModel(code = "WS", name = "Samoa", dialCode = "+685", icon = R.drawable.ws),
        CountryModel(code = "SM", name = "San Marino", dialCode = "+378", icon = R.drawable.sm),
        CountryModel(code = "ST", name = "Sao Tome & Principe", dialCode = "+239", icon = R.drawable.st),
        CountryModel(code = "SA", name = "Saudi Arabia", dialCode = "+966", icon = R.drawable.sa),
        CountryModel(code = "SN", name = "Senegal", dialCode = "+221", icon = R.drawable.sn),
        CountryModel(code = "RS", name = "Serbia", dialCode = "+381", icon = R.drawable.rs),
        CountryModel(code = "SC", name = "Seychelles", dialCode = "+248", icon = R.drawable.sc),
        CountryModel(code = "SL", name = "Sierra Leone", dialCode = "+232", icon = R.drawable.sl),
        CountryModel(code = "SG", name = "Singapore", dialCode = "+65", icon = R.drawable.sg),
        CountryModel(code = "SK", name = "Slovakia", dialCode = "+421", icon = R.drawable.sk),
        CountryModel(code = "SI", name = "Slovenia", dialCode = "+386", icon = R.drawable.si),
        CountryModel(code = "SB", name = "Solomon Islands", dialCode = "+677", icon = R.drawable.sb),
        CountryModel(code = "SO", name = "Somalia", dialCode = "+252", icon = R.drawable.so),
        CountryModel(code = "ZA", name = "South Africa", dialCode = "+27", icon = R.drawable.za),
        CountryModel(code = "ES", name = "Spain", dialCode = "+34", icon = R.drawable.es),
        CountryModel(code = "LK", name = "Sri Lanka", dialCode = "+94", icon = R.drawable.lk),
        CountryModel(code = "SD", name = "Sudan", dialCode = "+249", icon = R.drawable.sd),
        CountryModel(code = "SR", name = "Suriname", dialCode = "+597", icon = R.drawable.sr),
        CountryModel(code = "SZ", name = "Swaziland", dialCode = "+268", icon = R.drawable.sz),
        CountryModel(code = "SE", name = "Sweden", dialCode = "+46", icon = R.drawable.se),
        CountryModel(code = "CH", name = "Switzerland", dialCode = "+41", icon = R.drawable.ch),
        CountryModel(code = "SY", name = "Syria", dialCode = "+963", icon = R.drawable.sy),
        CountryModel(code = "TW", name = "Taiwan", dialCode = "+886", icon = R.drawable.tw),
        CountryModel(code = "TJ", name = "Tajikistan", dialCode = "+992", icon = R.drawable.tj),
        CountryModel(code = "TZ", name = "Tanzania", dialCode = "+255", icon = R.drawable.tz),
        CountryModel(code = "TH", name = "Thailand", dialCode = "+66", icon = R.drawable.th),
        CountryModel(code = "TL", name = "Timor-Leste", dialCode = "+670", icon = R.drawable.tl),
        CountryModel(code = "TG", name = "Togo", dialCode = "+228", icon = R.drawable.tg),
        CountryModel(code = "TK", name = "Tokelau", dialCode = "+690", icon = R.drawable.tk),
        CountryModel(code = "TO", name = "Tonga", dialCode = "+676", icon = R.drawable.to),
        CountryModel(code = "TT", name = "Trinidad & Tobago", dialCode = "+1868", icon = R.drawable.tt),
        CountryModel(code = "TN", name = "Tunisia", dialCode = "+216", icon = R.drawable.tn),
        CountryModel(code = "TR", name = "Turkey", dialCode = "+90", icon = R.drawable.tr),
        CountryModel(code = "TM", name = "Turkmenistan", dialCode = "+993", icon = R.drawable.tm),
        CountryModel(code = "TV", name = "Tuvalu", dialCode = "+688", icon = R.drawable.tv),
        CountryModel(code = "UG", name = "Uganda", dialCode = "+256", icon = R.drawable.ug),
        CountryModel(code = "UA", name = "Ukraine", dialCode = "+380", icon = R.drawable.ua),
        CountryModel(code = "AE", name = "United Arab Emirates", dialCode = "+971", icon = R.drawable.ae),
        CountryModel(code = "GB", name = "United Kingdom", dialCode = "+44", icon = R.drawable.gb),
        CountryModel(code = "US", name = "United States", dialCode = "+1", icon = R.drawable.us),
        CountryModel(code = "UY", name = "Uruguay", dialCode = "+598", icon = R.drawable.uy),
        CountryModel(code = "UZ", name = "Uzbekistan", dialCode = "+998", icon = R.drawable.uz),
        CountryModel(code = "VU", name = "Vanuatu", dialCode = "+678", icon = R.drawable.vu),
        CountryModel(code = "VE", name = "Venezuela", dialCode = "+58", icon = R.drawable.ve),
        CountryModel(code = "VN", name = "Vietnam", dialCode = "+84", icon = R.drawable.vn),
        CountryModel(code = "EH", name = "Western Sahara", dialCode = "+212", icon = R.drawable.eh),
        CountryModel(code = "YE", name = "Yemen", dialCode = "+967", icon = R.drawable.ye),
        CountryModel(code = "ZM", name = "Zambia", dialCode = "+260", icon = R.drawable.zm),
        CountryModel(code = "ZW", name = "Zimbabwe", dialCode = "+263", icon = R.drawable.zw)
    )
}